global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'local-spring-boot-multi-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080', 'host.docker.internal:8081', 'host.docker.internal:8082']

  - job_name: 'nodejs-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3001']
