global:
  scrape_interval: 5s

scrape_configs:
  - job_name: local-spring-boot-multi-services
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: risk-management-prometheus
      client_secret: 4xbiieTftRnJrSinfConWSmXnTfYa0B0
      token_url: http://host.docker.internal:9090/realms/velum/protocol/openid-connect/token
      scopes:
        - openid

    static_configs:
      - targets: ['host.docker.internal:8080', 'host.docker.internal:8081', 'host.docker.internal:8082']
